### PR TITLE
Prepare repo for translation

### PR DESCRIPTION
**Pull request by r0qs**
@faisalfh5, @Jawad0318 and @yousufkalim, we noticed that the initial repository setup wasn't completed, so I've taken care of it for you. Please refer to our [maintainer's guide](https://github.com/solidity-docs/.github/blob/main/maintainer-guide.md) from now on.

Furthermore, if you have any questions, feel free to reach out to us in the Matrix chat room at [Solidity Docs Community Translations](https://app.element.io/#/room/#solidity-docs-translations:matrix.org).

### CODE REVIEW

**Review by faisalfh5 — APPROVED** [review]
Thank you for taking care of the repository setup. I'll make sure to follow the maintainer's guide from now on. If I have any questions, I'll reach out to the Solidity Docs Community Translations Matrix chat room.

**Comment by AsharibAli** [comment]
@faisalfh5 Let's work together on it and divide the tasks to finish it. Please check your email.

**Comment by AsharibAli** [comment]
@faisalfh5 can you please look at your social handles or email? so we may collaborate and work on it!

**Comment by faisalfh5** [comment]
@AsharibAli Thank you for being willing to contribute to the Solidity translation. Currently, I don't have access to invite anyone to start contributing to the translation with us. I'll ask the @r0qs for access, and once I have it, I'll let you know.

**Comment by AsharibAli** [comment]
@faisalfh5 look at your facebook message box or email, I messaged you, so we may collaborate on it perfectly!

**Pull request merged**
